meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: jenkins
    template: jenkins_master
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))
